image: maven:latest
variables:
  SONAR_TOKEN: "016982f9c96375214474565fb61f1a8037d4909d"
  SONAR_HOST_URL: "https://sonarcloud.io"
  GIT_DEPTH: 0

sonarcloud-backend-location-service:
  stage: sonar-location
  script:
    - cd "${CI_PROJECT_DIR}/backend/location-service"
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=locationService
  allow_failure: true
  only:
    - merge_requests
    - main